export default {
  inter: {
    light: 'Inter-Light',
    regular: 'Inter-Regular',
    medium: 'Inter-Medium',
    semibold: 'Inter-SemiBold',
    bold: 'Inter-Bold',
    extrabold: 'Inter-ExtraBold',
    black: 'Inter-Black',
    300: 'Inter-Light',
    400: 'Inter-Regular',
    500: 'Inter-Medium',
    600: 'Inter-SemiBold',
    700: 'Inter-Bold',
    800: 'Inter-ExtraBold',
    900: 'Inter-Black',
  },
  karla: {
    light: 'Karla-Light',
    regular: 'Karla-Regular',
    medium: 'Karla-Medium',
    semibold: 'Karla-SemiBold',
    bold: 'Karla-Bold',
    extrabold: 'Karla-ExtraBold',
    black: 'Karla-Black',
    300: 'Karla-Light',
    400: 'Karla-Regular',
    500: 'Karla-Medium',
    600: 'Karla-SemiBold',
    700: 'Karla-Bold',
    800: 'Karla-ExtraBold',
    900: 'Karla-Black',
  },
};
